name: vc_super_app
description: "Production-level Flutter boilerplate."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  dio: ^5.9.2
  get_it: ^9.2.1
  flutter_riverpod: ^3.3.1
  go_router: ^17.1.0
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.0.0
  connectivity_plus: ^7.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  firebase_core: ^4.6.0
  firebase_analytics: ^12.2.0
  firebase_crashlytics: ^5.1.0
  firebase_messaging: ^16.1.3
  webview_flutter: ^4.13.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.13.1
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  shared_preferences: ^2.5.5
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true


